Don't su postgres on startup
Fixes:

    $ docker run -it --rm dalibo/temboardui-pg
    The files belonging to this database system will be owned by user "postgres".
    This user must also own the server process.

    The database cluster will be initialized with locale "en_US.utf8".
    The default database encoding has accordingly been set to "UTF8".
    The default text search configuration will be set to "english".

    Data page checksums are disabled.

    fixing permissions on existing directory /var/lib/postgresql/data ... ok
    creating subdirectories ... ok
    selecting default max_connections ... 100
    selecting default shared_buffers ... 128MB
    selecting dynamic shared memory implementation ... posix
    creating configuration files ... ok
    running bootstrap script ... ok
    performing post-bootstrap initialization ... ok
    syncing data to disk ... ok

    WARNING: enabling "trust" authentication for local connections
    You can change this by editing pg_hba.conf or using the option -A, or
    --auth-local and --auth-host, the next time you run initdb.

    Success. You can now start the database server using:

        pg_ctl -D /var/lib/postgresql/data -l logfile start

    ****************************************************
    WARNING: No password has been set for the database.
             This will allow anyone with access to the
             Postgres port to access your database. In
             Docker's default configuration, this is
             effectively any other container on the same
             system.

             Use "-e POSTGRES_PASSWORD=password" to set
             it in "docker run".
    ****************************************************
    waiting for server to start....LOG:  database system was shut down at 2017-03-17 11:56:27 UTC
    LOG:  MultiXact member wraparound protections are now enabled
    LOG:  database system is ready to accept connections
    LOG:  autovacuum launcher started
     done
    server started
    ALTER ROLE

    /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/setup_temboard.sh
    error: failed switching to "postgres": operation not permitted